### ISSUE TITLE
Notes:

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/OpenAgar#5]

**Comment by LegitSoulja** [comment]
Notes

# Windows

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn start ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by Andrews54757** [comment]
I hate windows. I fixed it. Run npm install

**Comment by LegitSoulja** [comment]
@Andrews54757 I wonder if nodejs can run on a windows 98 OS?

**Comment by LegitSoulja** [comment]
@Andrews54757 
> I hate windows. I fixed it. Run npm install

nope. It's still not fixed. Where does the error occur?

**Comment by LegitSoulja** [comment]
I can run on another OS, but I use windows for hosting. I've got best luck and control over windows, than an OS im not really familiar with.

**Comment by Andrews54757** [comment]
## Game mode notes:

**Comment by Andrews54757** [comment]
MiniGames Notes:

**Comment by Andrews54757** [comment]
# Key System Overhaul
