### ISSUE TITLE
Statistics.js Error

### ISSUE THREAD

**Issue by fayizan** [AJS-development/OpenAgar#76]
I tried open agar today but got an error 

![screenshot_51](https://user-images.githubusercontent.com/19163419/28703395-6fafe91e-7381-11e7-990a-392cba552d50.png)

**Comment by Andrews54757** [comment]
Thats @LegitSoulja debugging. @fayizan I finished the client mech, overhauls are coming.

**Comment by Andrews54757** [comment]
https://github.com/AJS-development/OpenAgar/pull/77

**Comment by fayizan** [comment]
ohh ok and wow Just read #77 Interesting

**Comment by LegitSoulja** [comment]
@Andrews54757 as you know, I've been resting before my surgery. I am not doing any debugging. This is an issue I assume that should be checked out.

Besides, you got the magic eye with figuring out my projects (Specifically).

**Comment by LegitSoulja** [comment]
He could've also done this when I updated php then reverted. It shouldn't be an issue no more, since I postponed making php compatible. (A lot of work).

Other than that, I haven't touched the API.

**Comment by fayizan** [comment]
phixed ?

**Comment by LegitSoulja** [comment]
@fayizan looks like something was failing. I checked, made a few changes to what I thought may be a problem. 

Should be fixed, idk. Can't test atm.

**Comment by LegitSoulja** [comment]
@Andrews54757 are you strictly using POST? Cause GET has been disabled for API requests. Could also be the issue.

**Comment by fayizan** [comment]
I tried but the error is still there : |

![screenshot_63](https://user-images.githubusercontent.com/19163419/28746730-878bfe6e-74ae-11e7-8808-56068394c368.png)

**Comment by LegitSoulja** [comment]
@fayizan just re-run again

**Comment by fayizan** [comment]
Re-Run or Reinstall ?

**Comment by fayizan** [comment]
bcoz I tried running it again but it shows the same error

**Comment by LegitSoulja** [comment]
Reinstalling would be pointless. Re-run after that error to bypass it.

**Comment by fayizan** [comment]
ohh ok got it

**Comment by LegitSoulja** [comment]
@Andrews54757 take a look at OAStats/Update when you get a chance. Idk what the problem is, because I'm not getting a precise error, only JSON. It can be anything.

**Comment by fayizan** [comment]
ok I rerun after the error and its running

**Comment by fayizan** [comment]
lol wat is this @LegitSoulja 

![screenshot_65](https://user-images.githubusercontent.com/19163419/28747189-d31ad41a-74b6-11e7-9fe2-032fbef6d4a4.png)

**Comment by fayizan** [comment]
![screenshot_66](https://user-images.githubusercontent.com/19163419/28747217-54fc28f8-74b7-11e7-98e1-8601d5d68bd6.png)

**Comment by LegitSoulja** [comment]
@fayizan few reasons
- high, low ping.
- client took to long to connect to server.
- you connected, but never made any actions (Was in another tab), idle protection?
- Could be an issue with our API. 

Any logged console messages?

**Comment by LegitSoulja** [comment]
And yes, that update error will occur because I cannot figure out the issue. Just ignore.

**Comment by fayizan** [comment]
This is logged in console : |
![screenshot_67](https://user-images.githubusercontent.com/19163419/28747245-eb224fa6-74b7-11e7-8b47-435897549184.png)

**Comment by LegitSoulja** [comment]
@fayizan yeah, idk. Some connection or ping issue. 

Andrew should be available shortly. He'll be able to debug the server, however I can't. 

It's hard for me to point out exactly what's going on.

**Comment by fayizan** [comment]
lol I recorded 
http://195.181.243.147/OpenAgar.mp4

**Comment by fayizan** [comment]
@LegitSoulja ok I will wait no problem : )

**Comment by Andrews54757** [comment]
@fayizan Yes, the stats error. I will fix it soon

**Comment by Andrews54757** [comment]
@LegitSoulja Its because of slickinject

**Comment by LegitSoulja** [comment]
@Andrews54757 oh. Right.

**Comment by Andrews54757** [comment]
@fayizan Fixed. Please update

**Comment by fayizan** [comment]
@Andrews54757 I updated and got a new error 

![screenshot_68](https://user-images.githubusercontent.com/19163419/28750845-ead9d124-7514-11e7-92da-44edcecd013e.png)

**Comment by fayizan** [comment]
@Andrews54757 wow thanks for the new client update and it look awesome : ) but a error 
![screenshot_76](https://user-images.githubusercontent.com/19163419/28755677-c0ca472e-757d-11e7-84df-fe97402bfedb.png)

**Comment by Andrews54757** [comment]
@fayizan I think I fixed it. Update

**Comment by fayizan** [comment]
another error while connecting on browser 

![screenshot_77](https://user-images.githubusercontent.com/19163419/28755754-7f0b95de-757f-11e7-8cf4-bb256d0eb407.png)

**Comment by Andrews54757** [comment]
@fayizan connect with ws://

**Comment by fayizan** [comment]
I did and connected but the cell isnt drawing : |

**Comment by Andrews54757** [comment]
press play

**Comment by fayizan** [comment]
ok found the problem, changing clientconfig value wont allow me to spawn

**Comment by Andrews54757** [comment]
@fayizan Fixed the stats's http problem

**Comment by Andrews54757** [comment]
Also, clientconfig is not implemented yet

**Comment by fayizan** [comment]
omg works so smooth and fine but the camera view is cancer XD pls fix

**Comment by fayizan** [comment]
I tried to connect with this link but not working only ws:// connect works
```http://opnagar.us/server/fzserver```

**Comment by Andrews54757** [comment]
I know. I dont know why it isnt fixed yet

**Comment by Andrews54757** [comment]
oh

**Comment by Andrews54757** [comment]
Fixed

**Comment by Andrews54757** [comment]
whats wrong with the camera

**Comment by Andrews54757** [comment]
@fayizan Our move code:

```
    function moveCamera() {
        let total = 0;
        let tX = 0;
        let tY = 0;
        playerCells.forEach((id) => {
            const node = allNodes[id];
            if (!node) return;
            total += node.size;
            tX += node.x;
            tY += node.y;
        });

        tX = tX / playerCells.length;
        tY = tY / playerCells.length;

        let newViewZoom = total;
        newViewZoom = Math.min(64 / newViewZoom, 1) ** 0.4 * viewRange();
        viewZoom = (9 * viewZoom + newViewZoom) / 10;
        //var x = Math.floor((stage.pivot.x + tX) / 2);
        // var y = Math.floor((stage.pivot.y + tY) / 2)

        //(0,0) for us is center of the screen
        stage.position.x = getDim().width >> 1;
        stage.position.y = getDim().height >> 1;
        // scale
        stage.scale.set(viewZoom, viewZoom);

        // remember, center anchor/origon is 0.5 

        //    stage.pivot.set(tX, tY);

        stage.pivot.x = (stage.pivot.x + tX) / 2;
        stage.pivot.y = (stage.pivot.y + tY) / 2;

        viewBox.width = renderer.width / viewZoom;
        viewBox.height = renderer.height / viewZoom;
        viewBox.x = tX - (viewBox.width >> 1);
        viewBox.y = tY - (viewBox.height >> 1);
    }
```

**Comment by Andrews54757** [comment]
Also fixed the opnagar.us/server issue. Stupid htaccess

**Comment by LegitSoulja** [comment]
@Andrews54757 without it, will be no security. You just gotta learn .htaccess more. I only know about 60% of it except Regex (Confusing).

I don't acknowledge this method though. I suggest a custom routing system. Use PHP to manage, whilst .htaccess will always report back to index if link is not a folder/file/directory.

/server/test would get read as GET["server"] whilst the value is test.

I'll implement, if really needed. We could however expand this further in the future.

And that camera bug, I think it's when your cells go out of view it acts up, and possibly break. Reproduce by eating a virus. I pointed that out a while ago.

**Comment by Andrews54757** [comment]
@LegitSoulja No, its not because it goes out of range. Its something to do with pixi

**Comment by Andrews54757** [comment]
Ah, divide by zero error. Interesting

**Comment by Andrews54757** [comment]
@LegitSoulja @fayizan Fixed the camera bug. Also includes the virus bug

**Comment by fayizan** [comment]
Thanks @Andrews54757
